export const projects = [
  {
    id: 1,
    img: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=800&q=80',
    alt: 'La Eternidad',
    category: 'Wedding Film',
    name: 'La Eternidad',
    year: '2024',
    desc: 'Una historia de amor inmortalizada en luz y sombra, capturada en las costas del Mediterráneo.',
  },
  {
    id: 2,
    img: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=80',
    alt: 'Voces del Silencio',
    category: 'Documentary',
    name: 'Voces del Silencio',
    year: '2023',
    desc: 'Documental sobre comunidades indígenas y la preservación de su cultura a través de la oralidad.',
  },
  {
    id: 3,
    img: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&q=80',
    alt: 'Horizonte',
    category: 'Commercial',
    name: 'Horizonte',
    year: '2024',
    desc: 'Campaña publicitaria de alto impacto para una firma de lujo, rodada en locaciones premium.',
  },
  {
    id: 4,
    img: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    alt: 'Noche Rota',
    category: 'Music Video',
    name: 'Noche Rota',
    year: '2023',
    desc: 'Videoclip visceral que mezcla neón y oscuridad, siguiendo la narrativa de un amor fragmentado.',
  },
  {
    id: 5,
    img: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=800&q=80',
    alt: 'Aurora',
    category: 'Short Film',
    name: 'Aurora',
    year: '2024',
    desc: 'Cortometraje ganador en el Festival de Cine Independiente, una oda a la luz del amanecer.',
  },
  {
    id: 6,
    img: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=1200&q=80',
    alt: 'Raíces',
    category: 'Documentary',
    name: 'Raíces',
    year: '2022',
    desc: 'Exploración visual de la identidad cultural latinoamericana a través de tradiciones ancestrales.',
  },
]
